### ISSUE TITLE
Database: overhaul

### ISSUE THREAD

**Issue by klimesf** [nette/docs#244] opened 2015-02-28 11:23 UTC
Rewrite the section and stick to the doc guidelines.

ref http://forum.nette.org/cs/17100-co-vylepsit-na-dokumentaci

**Comment by f3l1x** [comment] 2017-07-16 15:03
Database is completely rewritten, we can close it, right @dg?

**Comment by dg** [comment] 2017-07-16 16:20
It's just a bit rewritten, it still requires a lot of work, but the issue is of course unnecessary.

**Closed by dg** 2017-07-16 16:20 UTC
Labels: Area: Database, Type: Enhancement
